name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ember

  test-try:
    name: Scenario Tests
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default-with-jquery
          - ember-classic
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Try Scenario
        run: yarn ember try:one ${{ matrix.scenario }}
