name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: lint
      run: yarn lint:js
